In [ ]:
import numpy as np
n1 = np.zeros([5,5],dtype=(int))
n1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
import numpy as np
n2 = np.ones([5,5],dtype=(int))
n2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
import numpy as np
n3 = np.eye(5,5,k=0,dtype=(int))
n3

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
import numpy as np
n3 = np.eye(5,5,k=1,dtype=(int))
n3

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
import numpy as np
n3 = np.eye(5,5,k=-1,dtype=(int))
n3

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [ ]:
n5=np.array([[2,8,7,9],[4,9,8,7]])
n5

array([[2, 8, 7, 9],
       [4, 9, 8, 7]])

In [ ]:
n6=np.transpose(n5)
n6

array([[2, 4],
       [8, 9],
       [7, 8],
       [9, 7]])

In [ ]:
n8=np.array([[5,8,9,6],[8,7,3,6],[4,7,9,8],[2,4,1,5]])
n8

array([[5, 8, 9, 6],
       [8, 7, 3, 6],
       [4, 7, 9, 8],
       [2, 4, 1, 5]])

In [ ]:
n9=n8[1:2,0:2]
n9[0,1]=400
n9

array([[  8, 400]])

In [ ]:
#Pandas
# pandas for non matrix or tabular form

In [ ]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,3,4,5,70],'b':[2,10,20,100,200,56],'c':['$10','$23','$87','$79','$71','$32']})
df

a    b    c
0   1    2  $10
1   2   10  $23
2   3   20  $87
3   4  100  $79
4   5  200  $71
5  70   56  $32

In [ ]:
df.loc[1]

a      2
b     10
c    $23
Name: 1, dtype: object

In [ ]:
df.iloc[1]

a      2
b     10
c    $23
Name: 1, dtype: object

In [ ]:
df.loc[[1,3],['a','b','c']]

a    b    c
1  2   10  $23
3  4  100  $79

In [ ]:
cp=pd.read_table('http://bit.ly/chiporders')
cp.head(50)

order_id  quantity                              item_name  \
0          1         1           Chips and Fresh Tomato Salsa   
1          1         1                                   Izze   
2          1         1                       Nantucket Nectar   
3          1         1  Chips and Tomatillo-Green Chili Salsa   
4          2         2                           Chicken Bowl   
5          3         1                           Chicken Bowl   
6          3         1                          Side of Chips   
7          4         1                          Steak Burrito   
8          4         1                       Steak Soft Tacos   
9          5         1                          Steak Burrito   
10         5         1                    Chips and Guacamole   
11         6         1                   Chicken Crispy Tacos   
12         6         1                     Chicken Soft Tacos   
13         7         1                           Chicken Bowl   
14         7         1                    Chips and Guacamole   
15         8         1  Chips and Tomatillo-Green Chili Salsa   
16         8         1                        Chicken Burrito   
17         9         1                        Chicken Burrito   
18         9         2                            Canned Soda   
19        10         1                           Chicken Bowl   
20        10         1                    Chips and Guacamole   
21        11         1                       Barbacoa Burrito   
22        11         1                       Nantucket Nectar   
23        12         1                        Chicken Burrito   
24        12         1                                   Izze   
25        13         1           Chips and Fresh Tomato Salsa   
26        13         1                           Chicken Bowl   
27        14         1                       Carnitas Burrito   
28        14         1                            Canned Soda   
29        15         1                        Chicken Burrito   
30        15         1  Chips and Tomatillo-Green Chili Salsa   
31        16         1                          Steak Burrito   
32        16         1                          Side of Chips   
33        17         1                          Carnitas Bowl   
34        17         1                          Bottled Water   
35        18         1                     Chicken Soft Tacos   
36        18         1                     Chicken Soft Tacos   
37        18         1                    Chips and Guacamole   
38        18         1  Chips and Tomatillo Green Chili Salsa   
39        19         1                          Barbacoa Bowl   
40        19         1                                  Chips   
41        20         1                    Chips and Guacamole   
42        20         1                           Chicken Bowl   
43        20         1                          Steak Burrito   
44        20         1                     Chicken Salad Bowl   
45        21         1                        Chicken Burrito   
46        21         1                          Steak Burrito   
47        21         1                                   Izze   
48        22         1                          Steak Burrito   
49        22         1                    Chips and Guacamole   

                                   choice_description item_price  
0                                                 NaN     $2.39   
1                                        [Clementine]     $3.39   
2                                             [Apple]     $3.39   
3                                                 NaN     $2.39   
4   [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5   [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                 NaN     $1.69   
7   [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8   [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9   [Fresh Tomato 

In [ ]:
cp.describe()

order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [ ]:
cp[cp['quantity']==2]

order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
18           9         2         Canned Soda   
51          23         2         Canned Soda   
135         60         2  Chicken Salad Bowl   
148         67         2       Steak Burrito   
...        ...       ...                 ...   
4435      1767         2        Chicken Bowl   
4499      1789         2   Canned Soft Drink   
4560      1812         2   Canned Soft Drink   
4561      1813         2  Chicken Salad Bowl   
4582      1822         2       Bottled Water   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
18                                             [Sprite]     $2.18   
51                                       [Mountain Dew]     $2.18   
135   [Tomatillo Green Chili Salsa, [Sour Cream, Che...    $22.50   
148   [Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...    $17.98   
...                                                 ...        ...  
4435  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...    $17.50   
4499                                             [Coke]     $2.50   
4560                                             [Coke]     $2.50   
4561  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $17.50   
4582                                                NaN     $3.00   

[224 rows x 5 columns]

In [ ]:
cp[cp['quantity']==2].sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


order_id                                                 205258
quantity                                                    448
item_name     Chicken BowlCanned SodaCanned SodaChicken Sala...
item_price    $16.98 $2.18 $2.18 $22.50 $17.98 $17.50 $17.50...
dtype: object

In [ ]:
(cp['quantity']==2).sum()/len(cp)*100

4.846386845521419

In [ ]:
(cp['quantity']==2).sum()

224

In [ ]:
(cp['quantity']==1).sum()

4355

In [ ]:
(cp['item_name']=='Chicken Bowl').sum()

726

In [ ]:
(cp['item_name']=='Chicken Salad Bowl').sum()

110

In [ ]:
(cp['item_name']=='Chicken Burrito').sum()

553

In [ ]:
(cp['item_name']=='Chicken Crispy Tacos').sum()

47

In [ ]:
(cp['item_name']=='Chicken Soft Tacos').sum()

115

In [ ]:
cp[cp['item_name'].str.contains('Chicken')]

order_id  quantity             item_name  \
4            2         2          Chicken Bowl   
5            3         1          Chicken Bowl   
11           6         1  Chicken Crispy Tacos   
12           6         1    Chicken Soft Tacos   
13           7         1          Chicken Bowl   
...        ...       ...                   ...   
4604      1828         1          Chicken Bowl   
4615      1832         1    Chicken Soft Tacos   
4619      1834         1    Chicken Salad Bowl   
4620      1834         1    Chicken Salad Bowl   
4621      1834         1    Chicken Salad Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75   
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75   
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
...                                                 ...        ...  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75   
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $8.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[1560 rows x 5 columns]

In [ ]:
cp[cp['item_name'].str.contains('Chips')]

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
6            3         1                          Side of Chips   
10           5         1                    Chips and Guacamole   
14           7         1                    Chips and Guacamole   
...        ...       ...                                    ...   
4596      1826         1                    Chips and Guacamole   
4600      1827         1                    Chips and Guacamole   
4605      1828         1                    Chips and Guacamole   
4613      1831         1                                  Chips   
4616      1832         1                    Chips and Guacamole   

     choice_description item_price  
0                   NaN     $2.39   
3                   NaN     $2.39   
6                   NaN     $1.69   
10                  NaN     $4.45   
14                  NaN     $4.45   
...                 ...        ...  
4596                NaN     $4.45   
4600                NaN     $4.45   
4605                NaN     $4.45   
4613                NaN     $2.15   
4616                NaN     $4.45   

[1084 rows x 5 columns]

In [ ]:
cp[cp['item_name'].str.contains('Tomato')]

order_id  quantity                     item_name choice_description  \
0            1         1  Chips and Fresh Tomato Salsa                NaN   
25          13         1  Chips and Fresh Tomato Salsa                NaN   
55          25         1  Chips and Fresh Tomato Salsa                NaN   
89          39         1  Chips and Fresh Tomato Salsa                NaN   
183         82         1  Chips and Fresh Tomato Salsa                NaN   
...        ...       ...                           ...                ...   
4231      1689         1  Chips and Fresh Tomato Salsa                NaN   
4318      1722         1  Chips and Fresh Tomato Salsa                NaN   
4324      1725         1  Chips and Fresh Tomato Salsa                NaN   
4425      1764         1  Chips and Fresh Tomato Salsa                NaN   
4503      1790         1  Chips and Fresh Tomato Salsa                NaN   

     item_price  
0        $2.39   
25       $2.39   
55       $2.39   
89       $2.95   
183      $2.95   
...         ...  
4231     $2.95   
4318     $2.95   
4324     $2.95   
4425     $2.95   
4503     $2.95   

[111 rows x 5 columns]

In [ ]:
(cp['item_price']).sum()

'$2.39 $3.39 $3.39 $2.39 $16.98 $10.98 $1.69 $11.75 $9.25 $9.25 $4.45 $8.75 $8.75 $11.25 $4.45 $2.39 $8.49 $8.49 $2.18 $8.75 $4.45 $8.99 $3.39 $10.98 $3.39 $2.39 $8.49 $8.99 $1.09 $8.49 $2.39 $8.99 $1.69 $8.99 $1.09 $8.75 $8.75 $4.45 $2.95 $11.75 $2.15 $4.45 $11.25 $11.75 $8.75 $10.98 $8.99 $3.39 $8.99 $3.99 $8.99 $2.18 $10.98 $1.09 $8.99 $2.39 $9.25 $11.25 $11.75 $2.15 $4.45 $9.25 $11.25 $8.75 $8.99 $8.99 $3.39 $8.99 $10.98 $8.99 $1.69 $8.99 $3.99 $8.75 $4.45 $8.75 $8.75 $2.15 $8.75 $11.25 $2.15 $9.25 $8.75 $8.75 $9.25 $8.49 $8.99 $1.09 $9.25 $2.95 $11.75 $11.75 $9.25 $11.75 $4.45 $9.25 $4.45 $11.75 $8.75 $8.75 $4.45 $8.99 $8.99 $3.99 $8.49 $3.39 $8.99 $1.09 $9.25 $4.45 $8.75 $2.95 $4.45 $2.39 $8.49 $8.99 $8.49 $1.09 $8.99 $3.99 $8.75 $9.25 $4.45 $11.25 $4.45 $8.99 $1.09 $9.25 $2.95 $4.45 $11.75 $4.45 $8.49 $2.39 $10.98 $22.50 $11.75 $4.45 $11.25 $4.45 $11.25 $4.45 $11.25 $11.25 $11.75 $9.25 $4.45 $11.48 $17.98 $1.69 $17.50 $4.45 $8.49 $2.39 $17.50 $4.45 $4.45 $11.25 $11.75 $10.98 $8.

In [ ]:
cp[cp['item_name'].str.contains('Chicken')]

order_id  quantity             item_name  \
4            2         2          Chicken Bowl   
5            3         1          Chicken Bowl   
11           6         1  Chicken Crispy Tacos   
12           6         1    Chicken Soft Tacos   
13           7         1          Chicken Bowl   
...        ...       ...                   ...   
4604      1828         1          Chicken Bowl   
4615      1832         1    Chicken Soft Tacos   
4619      1834         1    Chicken Salad Bowl   
4620      1834         1    Chicken Salad Bowl   
4621      1834         1    Chicken Salad Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75   
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75   
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
...                                                 ...        ...  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75   
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $8.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[1560 rows x 5 columns]

In [ ]:
cp['item_price']=cp['item_price'].str.replace('$','')
cp

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN      2.39   
1                                          [Clementine]      3.39   
2                                               [Apple]      3.39   
3                                                   NaN      2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75   

[4622 rows x 5 columns]

In [ ]:
cp['item_name'].str.contains('Chicken').sum()/len(cp)*100

33.751622674167024

In [ ]:
cp.loc[45]

order_id                                                             21
quantity                                                              1
item_name                                               Chicken Burrito
choice_description    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
item_price                                                       10.98 
Name: 45, dtype: object

In [ ]:
cp.loc[45]['item_name']

'Chicken Burrito'

In [ ]:
cp['item_price']=cp['item_price'].astype(float)
cp

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [ ]:
cp['item_price'].sum()

34500.16

In [ ]:
import pandas as pd
cp['item_price'].idxmax()

3598

In [ ]:
cp.loc[3598]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

In [ ]:
print(cp['item_price'].max())
print(cp['item_price'].min())

44.25
1.09


In [ ]:
cp['item_price'].value.counts()

AttributeError: ignored

In [ ]:
cp.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
print(cp.shape)
print(cp.columns)
cpc=cp.dropna(axis=1)
print(cpc.shape)
print(cpc.columns)

(4622, 5)
Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')
(4622, 4)
Index(['order_id', 'quantity', 'item_name', 'item_price'], dtype='object')


In [ ]:
cp['choice_description'].fillna('abcd')

0                                                    abcd
1                                            [Clementine]
2                                                 [Apple]
3                                                    abcd
4       [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
                              ...                        
4617    [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...
4618    [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4619    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
4620    [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...
4621    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
Name: choice_description, Length: 4622, dtype: object

In [2]:
import pandas as pd
movies = pd.read_csv('http://bit.ly/imdbratings')
movies.head(30)

star_rating                                              title  \
0           9.3                           The Shawshank Redemption   
1           9.2                                      The Godfather   
2           9.1                             The Godfather: Part II   
3           9.0                                    The Dark Knight   
4           8.9                                       Pulp Fiction   
5           8.9                                       12 Angry Men   
6           8.9                     The Good, the Bad and the Ugly   
7           8.9      The Lord of the Rings: The Return of the King   
8           8.9                                   Schindler's List   
9           8.9                                         Fight Club   
10          8.8  The Lord of the Rings: The Fellowship of the Ring   
11          8.8                                          Inception   
12          8.8     Star Wars: Episode V - The Empire Strikes Back   
13          8.8                                       Forrest Gump   
14          8.8              The Lord of the Rings: The Two Towers   
15          8.7                                       Interstellar   
16          8.7                    One Flew Over the Cuckoo's Nest   
17          8.7                                      Seven Samurai   
18          8.7                                         Goodfellas   
19          8.7                                          Star Wars   
20          8.7                                         The Matrix   
21          8.7                                        City of God   
22          8.7                              It's a Wonderful Life   
23          8.7                                 The Usual Suspects   
24          8.7                                              Se7en   
25          8.6                                  Life Is Beautiful   
26          8.6                       Once Upon a Time in the West   
27          8.6                           The Silence of the Lambs   
28          8.6                             Leon: The Professional   
29          8.6                                        City Lights   

   content_rating      genre  duration  \
0               R      Crime       142   
1               R      Crime       175   
2               R      Crime       200   
3           PG-13     Action       152   
4               R      Crime       154   
5       NOT RATED      Drama        96   
6       NOT RATED    Western       161   
7           PG-13  Adventure       201   
8               R  Biography       195   
9               R      Drama       139   
10          PG-13  Adventure       178   
11          PG-13     Action       148   
12             PG     Action       124   
13          PG-13      Drama       142   
14          PG-13  Adventure       179   
15          PG-13  Adventure       169   
16              R      Drama       133   
17        UNRATED      Drama       207   
18              R  Biography       146   
19             PG     Action       121   
20              R     Action       136   
21              R      Crime       130   
22       APPROVED      Drama       130   
23              R      Crime       106   
24              R      Drama       127   
25          PG-13     Comedy       116   
26          PG-13    Western       175   
27              R      Drama       118   
28              R      Crime       110   
29         PASSED     Comedy        87   

                                          actors_list  
0   [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1     [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2   [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3   [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4   [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5   [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
6   [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
7   [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
8   [u'Liam Neeson', u'Ral

In [3]:
import pandas as pd
movies['duration'].idxmax()

476

In [7]:
movies['duration'].max()

242

In [8]:
movies[movies['actors_list'].str.contains('Christian Bale')]['title']

3            The Dark Knight
43     The Dark Knight Rises
53              The Prestige
113            Batman Begins
446              The Fighter
504        Empire of the Sun
555             3:10 to Yuma
589            The Machinist
702    Jin ling shi san chai
732          American Psycho
815              Equilibrium
Name: title, dtype: object

In [4]:
movies.loc[476]

star_rating                                                     7.8
title                                                        Hamlet
content_rating                                                PG-13
genre                                                         Drama
duration                                                        242
actors_list       [u'Kenneth Branagh', u'Julie Christie', u'Dere...
Name: 476, dtype: object

In [5]:
movies.isnull().sum()

star_rating       0
title             0
content_rating    3
genre             0
duration          0
actors_list       0
dtype: int64

In [6]:
movies[((movies['genre']=='Crime')|(movies['genre']=='Comedy')|(movies['genre']=='Action')) & (movies['duration']<160) &(movies['star_rating']>8)]

star_rating                                           title  \
0            9.3                        The Shawshank Redemption   
3            9.0                                 The Dark Knight   
4            8.9                                    Pulp Fiction   
11           8.8                                       Inception   
12           8.8  Star Wars: Episode V - The Empire Strikes Back   
..           ...                                             ...   
285          8.1                                Bringing Up Baby   
287          8.1                                 His Girl Friday   
290          8.1                                       Prisoners   
293          8.1                                       Duck Soup   
296          8.1                                  The Wild Bunch   

    content_rating   genre  duration  \
0                R   Crime       142   
3            PG-13  Action       152   
4                R   Crime       154   
11           PG-13  Action       148   
12              PG  Action       124   
..             ...     ...       ...   
285       APPROVED  Comedy       102   
287       APPROVED  Comedy        92   
290              R   Crime       153   
293         PASSED  Comedy        68   
296              R  Action       145   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
11   [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...  
12   [u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...  
..                                                 ...  
285  [u'Katharine Hepburn', u'Cary Grant', u'Charle...  
287  [u'Cary Grant', u'Rosalind Russell', u'Ralph B...  
290  [u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ...  
293    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
296  [u'William Holden', u'Ernest Borgnine', u'Robe...  

[102 rows x 6 columns]

In [ ]:
import pandas as pandas
covid = pd.read_csv('/content/country_wise_latest.csv')
covid.head(10)

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0          Afghanistan      36263    1269      25198    9796        106   
1              Albania       4880     144       2745    1991        117   
2              Algeria      27973    1163      18837    7973        616   
3              Andorra        907      52        803      52         10   
4               Angola        950      41        242     667         18   
5  Antigua and Barbuda         86       3         65      18          4   
6            Argentina     167416    3059      72575   91782       4890   
7              Armenia      37390     711      26665   10014         73   
8            Australia      15303     167       9311    5825        368   
9              Austria      20558     713      18246    1599         86   

   New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0          10             18                3.50                  69.49   
1           6             63                2.95                  56.25   
2           8            749                4.16                  67.34   
3           0              0                5.73                  88.53   
4           1              0                4.32                  25.47   
5           0              5                3.49                  75.58   
6         120           2057                1.83                  43.35   
7           6            187                1.90                  71.32   
8           6            137                1.09                  60.84   
9           1             37                3.47                  88.75   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1                    5.25                 4171            709   
2                    6.17                23691           4282   
3                    6.48                  884             23   
4                   16.94                  749            201   
5                    4.62                   76             10   
6                    4.21               130774          36642   
7                    2.67                34981           2409   
8                    1.79                12428           2875   
9                    3.91                19743            815   

   1 week % increase             WHO Region  
0               2.07  Eastern Mediterranean  
1              17.00                 Europe  
2              18.07                 Africa  
3               2.60                 Europe  
4              26.84                 Africa  
5              13.16               Americas  
6              28.02               Americas  
7               6.89                 Europe  
8              23.13        Western Pacific  
9               4.13                 Europe

In [ ]:
(movies['genre']=='Crime').sum()

124

In [ ]:
(movies['genre']=='Crime')|(movies['genre']=='Action') & (movies['duration']<160)]

SyntaxError: ignored

In [ ]:
movies['genre'].isin('Crime'|'Comedy'|'Action')

TypeError: ignored

In [ ]:
import pandas as pandas
cgeo = pd.read_csv('/content/geography.csv')
cgeo.head(30)

location_key  openstreetmap_id   latitude  longitude  elevation_m  \
0            AD            9407.0  42.558333   1.555278          NaN   
1            AE          307763.0  24.400000  54.300000          NaN   
2            AF          303427.0  33.000000  66.000000          NaN   
3        AF_BAL         1674795.0  36.700000  67.116667        340.0   
4        AF_BAM               NaN  34.750000  67.250000       3042.0   
5        AF_BDG               NaN  35.000000  63.750000       1589.0   
6        AF_BDS               NaN  38.000000  71.000000       3669.0   
7        AF_BGL               NaN  35.870000  68.930000       2013.0   
8        AF_DAY               NaN  33.750000  66.250000       2200.0   
9        AF_FRA         1674802.0  32.500000  63.500000       1081.0   
10       AF_FYB               NaN  36.000000  65.000000        584.0   
11       AF_GHA               NaN  33.500000  68.000000       3238.0   
12       AF_GHO               NaN  34.519722  65.255000       2831.0   
13       AF_HEL         1674573.0  31.000000  64.000000        725.0   
14       AF_HER               NaN  34.000000  62.000000       1088.0   
15       AF_JOW               NaN  36.750000  66.000000        309.0   
16       AF_KAB               NaN  34.560000  69.220000       1908.0   
17       AF_KAN               NaN  31.000000  65.500000       1216.0   
18       AF_KAP               NaN  35.000000  69.700000       1746.0   
19       AF_KDZ         1674564.0  36.800000  68.800000        379.0   
20       AF_KHO               NaN  33.400000  69.900000       1286.0   
21       AF_KNR               NaN  35.000000  71.200000       1906.0   
22       AF_LAG               NaN  34.660000  70.200000       1592.0   
23       AF_LOG               NaN  34.000000  69.200000       2370.0   
24       AF_NAN               NaN  34.250000  70.500000        748.0   
25       AF_NIM         1674664.0  31.000000  62.500000        610.0   
26       AF_NUR         1674544.0  35.250000  70.750000       3471.0   
27       AF_PAN               NaN  35.427500  69.735000       4226.0   
28       AF_PAR               NaN  35.000000  69.000000       1906.0   
29       AF_PIA               NaN  33.600000  69.500000       2409.0   

    area_sq_km  area_rural_sq_km  area_urban_sq_km  
0        470.0               NaN               NaN  
1      83600.0           70575.0            8568.0  
2     652860.0               NaN               NaN  
3      16186.0               NaN               NaN  
4      14175.0               NaN               NaN  
5      20591.0               NaN               NaN  
6      44059.0               NaN               NaN  
7      21118.0               NaN               NaN  
8      18088.0               NaN               NaN  
9      48470.0               NaN               NaN  
10     20293.0               NaN               NaN  
11     22915.0               NaN               NaN  
12     36479.0               NaN               NaN  
13     58584.0               NaN               NaN  
14     54778.0               NaN               NaN  
15     11798.0               NaN               NaN  
16      4461.0               NaN               NaN  
17     54022.0               NaN               NaN  
18      1842.0               NaN               NaN  
19      8040.0               NaN               NaN  
20      4151.0               NaN               NaN  
21      4339.0               NaN               NaN  
22      3843.0               NaN               NaN  
23      3879.0               NaN               NaN  
24      7727.0               NaN               NaN  
25     41356.0               NaN               NaN  
26      9225.0               NaN               NaN  
27      3610.0               NaN               NaN  
28      5974.0               NaN               NaN  
29      6432.0               NaN               NaN