In [ ]:
import numpy as np
import random
a=np.random.randint(0,2,[50,20])
random.sample(range(0,10),10)

[6, 8, 2, 4, 9, 3, 0, 7, 1, 5]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
b=np.random.randint(0,10,5)
b

array([5, 0, 3, 7, 5])

In [ ]:
a=np.random.randint(0,7,[50,20])
a

array([[4, 2, 6, 1, 3, 6, 4, 4, 5, 0, 5, 1, 2, 4, 1, 1, 3, 2, 3, 2],
       [4, 4, 1, 1, 1, 3, 5, 3, 1, 0, 6, 4, 3, 1, 2, 3, 3, 5, 4, 6],
       [2, 0, 0, 1, 3, 2, 1, 5, 4, 0, 3, 1, 3, 5, 6, 4, 6, 4, 4, 2],
       [2, 2, 3, 1, 5, 1, 0, 3, 5, 1, 3, 2, 1, 2, 5, 2, 5, 1, 6, 4],
       [4, 6, 2, 1, 3, 0, 4, 6, 5, 6, 1, 3, 6, 3, 5, 1, 5, 1, 6, 1],
       [3, 2, 5, 3, 2, 0, 3, 5, 6, 4, 2, 1, 2, 0, 6, 6, 1, 5, 2, 6],
       [3, 5, 4, 6, 6, 6, 1, 1, 6, 4, 0, 3, 5, 3, 3, 5, 0, 3, 2, 4],
       [3, 3, 1, 6, 1, 1, 0, 2, 0, 3, 6, 3, 2, 4, 0, 1, 5, 2, 0, 1],
       [3, 1, 4, 5, 6, 1, 1, 2, 1, 0, 0, 6, 0, 5, 0, 2, 2, 6, 6, 4],
       [1, 4, 5, 5, 4, 4, 5, 3, 5, 1, 3, 2, 1, 2, 5, 3, 4, 5, 1, 4],
       [6, 0, 6, 0, 6, 1, 5, 1, 3, 1, 6, 4, 4, 0, 4, 3, 2, 6, 2, 4],
       [1, 6, 2, 5, 6, 6, 1, 3, 1, 5, 4, 4, 1, 1, 0, 3, 5, 1, 0, 6],
       [3, 4, 4, 0, 4, 2, 3, 2, 2, 5, 4, 5, 2, 6, 0, 0, 4, 5, 0, 4],
       [1, 2, 5, 1, 1, 3, 2, 6, 6, 5, 2, 3, 6, 3, 3, 5, 0, 5, 1, 5],
       [1, 5, 6, 0, 2, 4, 4, 4, 3,

In [ ]:
import random
random.sample(range(0,10),7)

[2, 5, 1, 3, 4, 9, 8]

In [ ]:
in1=np.where(b>=5)
in1[0]

array([0, 3, 4])

In [ ]:
fname='filloc'+str(1)+'.csv'
data=np.genfromtxt(fname,delimiter=',')
data

In [ ]:
np.shape(data)

In [ ]:
def impfeat(data):
  nof=np.shape(data)[1]-1
  pla=data[:,-1]
  in1=np.where(pla==0)
  in2=np.where(pla==1)
  p=np.zeroes((20))
  for i in range(0,nof):
    f=data[:,i]
    f1=f[in1[0]]
    f2=f[in2[0]]
    b=ranksums(f1,f2)
    p[i]=b.pvalue
  return p


In [ ]:
for i in range(11,52):
  fname='filloc'+str(1)+'.csv'
  data=np.genfromtxt(fname,delimiter=',')
  print(np.shape(data)[0])
  p=impfeat(data)
  in1=np.where(p<=0.05)
  dataf=data[:,in1[0]]
  dataf=np.concatenate((dataf.data[:,-1].reshape(-1,1)), axis=1)
  fname='filloc'+str(51+i)+'.csv'
  np.savetxt(fname,dataf,delimiter=',',fmt='&f')
  print(len(in1[0]))

In [ ]:
from scipy.stats import ranksums
b=ranksums(a,a)
b 

In [ ]:
p=impfeat(data)
p

In [ ]:
in1=np.where(p<=0.05)
in1[0]
len(in1[0])