In [ ]:
#while

#Function
# f(x)=2x+3
#print(i,end="")--->end='' indicates that the end characterhas to be identified by whitespace and not a new line


In [ ]:
i=0
name=input('enter name')
while(name=='jay'):
  print('Good Morning',name)
  i=i+1
  if(i==11):
    break

enter namejay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay
Good Morning jay


In [ ]:
#f(x)=2x+3

In [ ]:
def fun(x,y):
  print(x)

In [ ]:
fun(2,3)

2


In [ ]:
# Program to find the sum of all numbers stored in a list

# List of numbers
numbers = [6, 5, 3, 8, 4, 2, 5, 4, 11]

# variable to store the sum
sum = 0

# iterate over the list
for val in numbers:
    sum = sum+val

print("The sum is", sum)

The sum is 48


In [ ]:
print(range(10))

print(list(range(10)))

print(list(range(2, 8)))

print(list(range(2, 20, 3)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7]
[2, 5, 8, 11, 14, 17]


In [ ]:
for i in range(2,100,2):
  print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [ ]:

item = [0, 1, 5]

for i in item:
    print(i)
else:
    print("No items left.")

0
1
5
No items left.


In [ ]:
for i in range(0,5):
  for j in range(0,i+1):
    print(i,end="")

  print('\r')#\r ->ending line after each row

0
11
222
3333
44444


In [ ]:
name=input('Enter Name')
i=0;
while(name=='jay'):
  print('hello !jay how are you')
  i+=1
  if(i==10):
    break



Enter Namejay
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you


In [ ]:
#Function
# f(x)=2x+3
#print(i,end="")--->end='' indicates that the end characterhas to be identified by whitespace and not a new line

In [ ]:
def sum():
  print('hello')

In [ ]:
sum()

hello


In [ ]:
def fun():
  name=input('Enter Name')
  i=0;
  while(name=='jay'):
    print('hello !jay how are you')
    i+=1
    if(i==10):
      break

In [ ]:
fun()

Enter Namejay
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you
hello !jay how are you


In [ ]:
def add(a,b):
  c=a+b;
  print(c)

In [ ]:
a=int(input('enter value of a'))
b=int(input('enter value of b'))
add(a,b)

enter value of a20
enter value of b30
50


In [ ]:
def factorial(n):
  if n==1:
    return 1
  else:
    return n* factorial(n-1)

In [ ]:
factorial(5)

120

In [ ]:

def factorial(m):
  fact=1
  for i in range(1,m+1):
    fact=fact*i
  print(fact)

In [ ]:
factorial(5)

120


In [ ]:
def fact1(n1):
  if n1==1:
    return 1
  else:
    return n1*fact1(n1-1)


In [ ]:
n1=int(input('enter value of n1'))
fact1(n1)

enter value of n15


120

In [ ]:
#File handling

In [ ]:
f1=open('file1.txt','w')
f1.write('hello india')
f1.close()

In [ ]:
t1=open('file1.txt','r')
print(t1.read())

hello india


In [ ]:
# Now we will understand certain Libraries
#N dimensional mathematical operations
#N dimensional matrix
# When we discuss N dimentional matrix we need library to deal with it
# Numpy -->Numerical Python
#Pandas are basically the libraries to deal with datasets
#To extract useful data fom datasets
#Matplotlib --> Plotting the data on x and y axis

In [ ]:
l=[2,4,6,8,16]
for i in range(0,len(l)):
  l[i]=l[i]*2
print(l)

[4, 8, 12, 16, 32]


In [ ]:
import numpy as np

In [ ]:
#if list is there then why numpy

In [ ]:
l=[2,8,3,6,7]
l*2

[2, 8, 3, 6, 7, 2, 8, 3, 6, 7]

In [ ]:
k=[]
for i in l:
  k.append(i*2)
k

[4, 16, 6, 12, 14]

In [ ]:
import numpy as np

In [ ]:
n2=np.array([[2,3,5,6],[2,8,9,10],[12,16,32,40]])
n2



array([[ 2,  3,  5,  6],
       [ 2,  8,  9, 10],
       [12, 16, 32, 40]])

In [ ]:
#array([[2, 3,  5,  6],
#      [ 2,  8,  9, 10],
#      [12, 16, 32, 40]])

In [ ]:
n2[0:2,1:3]

array([[3, 5],
       [8, 9]])

In [ ]:
n1=np.array([2,8,9,15,30])
n1*2

array([ 4, 16, 18, 30, 60])

In [ ]:
n1[1:3]

array([8, 9])

In [ ]:
#Numpy functions
#.array() #.reshape() #.max() #.min() #.argmax() # .argmin()
#.mean() #.std() # .sum() #.dot() #.hstack() # .vstack()
#.ones() #.zeros() #.eye()
#np.max(n1)


In [ ]:
#Attributes
#.shape #.size #.ndim
# n1.shape

In [ ]:
#multi dimensional arrays are knows matrix
#multi dimensional matrix are knows as tensor

In [ ]:
n2=np.array([[2,8,16,32],[12,14,17,18],[12,80,102,105]])
n2

array([[  2,   8,  16,  32],
       [ 12,  14,  17,  18],
       [ 12,  80, 102, 105]])

In [ ]:
n3=np.array([[[2,8,12,30],[12,16,20,40],[2,4,6,8]],
             [[2,8,9,5],[20,40,80,90],[80,100,200,300]],
             [[102,100,123,145],[103,102,100,105],[200,500,700,900]]])
n3

array([[[  2,   8,  12,  30],
        [ 12,  16,  20,  40],
        [  2,   4,   6,   8]],

       [[  2,   8,   9,   5],
        [ 20,  40,  80,  90],
        [ 80, 100, 200, 300]],

       [[102, 100, 123, 145],
        [103, 102, 100, 105],
        [200, 500, 700, 900]]])

In [ ]:
n3[0:3,1:3,2:4]

array([[[ 20,  40],
        [  6,   8]],

       [[ 80,  90],
        [200, 300]],

       [[100, 105],
        [700, 900]]])

In [ ]:
n1=np.array([2,8,9,15,30])

n2=np.array([[2,8,16,32],[12,14,17,18],[12,80,102,105]])

n3=np.array([[[2,8,12,30],[12,16,20,40],[2,4,6,8]],
             [[2,8,9,5],[20,40,80,90],[80,100,200,300]],
             [[102,100,1,145],[103,102,100,105],[200,500,700,900]]])


In [ ]:
import numpy as np

In [ ]:
print(np.max(n1))
print(np.max(n2))
print(np.max(n3))

30
105
900


In [ ]:
import numpy as np

In [ ]:
print(np.argmin(n1))
print(np.argmin(n2))
print(np.argmin(n3))

0
0
26


In [ ]:
print(np.max(n1))
print(np.min(n1))
print(np.std(n1))

30
2
9.53729521405309


In [ ]:
print(n3.shape)
print(n3.size)
print(n3.ndim)

(3, 3, 4)
36
3


In [ ]:
#slicing in 2-dimension
#n2[row slice,column slic]
#n2[1:3,4:6]

In [ ]:
#slicing in 3-dimension
#n3[floor slice, row slice, column slice]
#n3[:,:,:]

In [ ]:
#combining two different matrices
#.vstack()--->if number of column same
#.hstack()----> if number of rows same

In [ ]:
import numpy as np
a=np.array([[1,4,6,9],
            [2,4,6,8]])
b=np.array([2,6,8,7])
d=np.array([[1,3,4],[2,7,9]])

In [ ]:
f=np.hstack((a,d))
f

array([[1, 4, 6, 9, 1, 3, 4],
       [2, 4, 6, 8, 2, 7, 9]])

In [ ]:
c=np.vstack((a,b))
c

array([[1, 4, 6, 9],
       [2, 4, 6, 8],
       [2, 6, 8, 7]])

In [ ]:
a

array([[1, 4, 6, 9],
       [2, 4, 6, 8]])

In [ ]:
b

array([[2, 6, 8, 7]])

In [ ]:
c=np.vstack((a,b))
c

array([[1, 4, 6, 9],
       [2, 4, 6, 8],
       [2, 6, 8, 7]])

In [ ]:
d=np.array([[2,3,5],[1,9,8]])

In [ ]:
e=np.hstack((a,d))
e

array([[1, 4, 6, 9, 2, 3, 5],
       [2, 4, 6, 8, 1, 9, 8]])

In [ ]:
m=np.array([[2,4,6,8],[2,8,9,1]])
p=np.array([[2,6,7,9],[1,5,8,10]])

In [ ]:
s=np.hstack((m,p))
h=np.vstack((m,p))

In [ ]:
print(s)
print(h)

[[ 2  4  6  8  2  6  7  9]
 [ 2  8  9  1  1  5  8 10]]
[[ 2  4  6  8]
 [ 2  8  9  1]
 [ 2  6  7  9]
 [ 1  5  8 10]]
