In [ ]:
#Numpy functions
#.array() #.reshape() #.max() #.min() #.argmax() # .argmin()
#.mean() #.std() # .sum() #.dot() #.hstack() # .vstack()
#.ones() #.zeros() #.eye()
#np.max(n1)

In [ ]:
import numpy as np

n1=np.zeros([5,5],dtype=(int))
n1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
n3=np.array([[2,3,4,5],[3,4,7,82],[2,4,6,100]])
print(n3)

[[  2   3   4   5]
 [  3   4   7  82]
 [  2   4   6 100]]


In [ ]:
n3.reshape(12,1)

array([[  2],
       [  3],
       [  4],
       [  5],
       [  3],
       [  4],
       [  7],
       [ 82],
       [  2],
       [  4],
       [  6],
       [100]])

In [ ]:
n2=np.transpose(n3)
n2

array([[2, 3],
       [3, 4],
       [4, 7],
       [5, 8]])

In [ ]:
n1=np.eye(5,5,k=-4,dtype=(int))
n1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
n2=np.ones([5,5],dtype=(int))
print(n2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
n3=np.ones([5,5],dtype=int)
n3

In [ ]:
n1=np.array([[2,5,10,12,60],[2,6,7,8,9]])

In [ ]:
n1.reshape(5,2)

ValueError: ignored

In [ ]:
n2=np.transpose(n1)
n2

array([[ 2,  2],
       [ 5,  6],
       [10,  7],
       [12,  8],
       [60,  9]])

In [ ]:
n1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
n1=np.array([[2,4,5,6],[2,6,7,8],[2,3,4,5]])
n1

array([[2, 4, 5, 6],
       [2, 6, 7, 8],
       [2, 3, 4, 5]])

In [ ]:
n2=n1[1:2,0:2].copy()
n2[0,1]=600
n2

array([[  2, 600]])

In [ ]:
n1

array([[  2,   4,   5,   6],
       [  2, 400,   7,   8],
       [  2,   3,   4,   5]])

In [ ]:
n1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
n1

array([[  2,   5,  10,  12,  60],
       [  2, 100,   7,   8,   9]])

In [ ]:
n2=np.array([[1,2,6,8,9],[1,2,3,6,8]])
n2=n2.reshape(5,2)
n2

array([[1, 2],
       [6, 8],
       [9, 1],
       [2, 3],
       [6, 8]])

In [ ]:
n1.dot(n2)

array([[506, 570],
       [735, 907]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
n3=np.zeros([5,5],dtype=int)
n3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) 
#The eye tool returns a 2-D array with  1’s as the diagonal 
#and  0’s elsewhere. 
#The diagonal can be main, upper, or lower depending 
#on the optional parameter k. 
#A positive k is for the upper diagonal, 
#a negative k is for the lower, 
#and a  0 k (default) is for the main diagonal.

In [ ]:
n3=np.eye(5,5,k=0,dtype=int)
n3

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
n3=np.eye(5,5,k=1,dtype=int)
n3

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
#Pandas
# in Numpy data to be in matrix form
#pandas for non matrix or tabular form

In [ ]:
import pandas as pd
data=pd.DataFrame({'a':[1,2,4,6,9],'b':[3,9,10,12,15],'c':['$ 10','$ 200','$ 300','$ 12','$ 50']},index=[1,2,3,4,5])
data

a   b      c
1  1   3   $ 10
2  2   9  $ 200
3  4  10  $ 300
4  6  12   $ 12
5  9  15   $ 50

In [ ]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,4,5,70],'b':[2,10,20,100,200],'c':['$ 2','$ 5','$ 10','$ 20','$ 30']},)#index=[1,2,3,4,5])

In [ ]:
data[['a','b','c']]

a   b      c
0  1   3   $ 10
1  2   9  $ 200
2  4  10  $ 300
3  6  12   $ 12
4  9  15   $ 50

In [ ]:
print(df)

    a    b     c
0   1    2   $ 2
1   2   10   $ 5
2   4   20  $ 10
3   5  100  $ 20
4  70  200  $ 30


In [ ]:
#.loc()--->Location
#.iloc()--->index location---always returns default index value i.e starting from 0

In [ ]:
df[['a','b','c']]

a    b     c
0   1    2   $ 2
1   2   10   $ 5
2   4   20  $ 10
3   5  100  $ 20
4  70  200  $ 30

In [ ]:
df.loc[1]

a      2
b     10
c    $ 5
Name: 1, dtype: object

In [ ]:
df.iloc[1]

a      2
b     10
c    $ 5
Name: 1, dtype: object

In [ ]:
df1=pd.DataFrame({'a':[1,2,5,6,7],'b':[30,20,10,12,25],'c':['$ 2','$ 20','$ 30','$ 50','$ 100']},index=[1,2,3,4,5])

In [ ]:
df1

a   b      c
1  1  30    $ 2
2  2  20   $ 20
3  5  10   $ 30
4  6  12   $ 50
5  7  25  $ 100

In [ ]:
df1.loc[1]

a      1
b     30
c    $ 2
Name: 1, dtype: object

In [ ]:
df1.iloc[1]

a       2
b      20
c    $ 20
Name: 2, dtype: object

In [ ]:
# Selecting multiple rows and columns

In [ ]:
data.iloc[1:3,0:2]

a   b
2  2   9
3  4  10

In [ ]:
df.iloc[0:2,0:2]

a   b
0  1   2
1  2  10

In [ ]:
df.iloc[0:2,0:2]

a   b
0  1   2
1  2  10

In [ ]:
# Discontinuous selection

In [ ]:
data.loc[[1,3],['a','c']]

a      c
1  1   $ 10
3  4  $ 300

In [ ]:
# Now we will work on real dataset
# We can use dataset available with is directly from the cloud server
# search over internet read functions in pandas

In [ ]:
cp=pd.read_table('http://bit.ly/chiporders')
cp.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [ ]:
#items which has been ordered in quantity 2
#percentage of time order made is 2
#items ordered with chicken present as one of itsingredients
# .str.contains()
#Dealing with null values
#Average and sum of price values of all ordered items

In [ ]:
cp[cp['quantity']==2]


order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
18           9         2         Canned Soda   
51          23         2         Canned Soda   
135         60         2  Chicken Salad Bowl   
148         67         2       Steak Burrito   
...        ...       ...                 ...   
4435      1767         2        Chicken Bowl   
4499      1789         2   Canned Soft Drink   
4560      1812         2   Canned Soft Drink   
4561      1813         2  Chicken Salad Bowl   
4582      1822         2       Bottled Water   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
18                                             [Sprite]     $2.18   
51                                       [Mountain Dew]     $2.18   
135   [Tomatillo Green Chili Salsa, [Sour Cream, Che...    $22.50   
148   [Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...    $17.98   
...                                                 ...        ...  
4435  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...    $17.50   
4499                                             [Coke]     $2.50   
4560                                             [Coke]     $2.50   
4561  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $17.50   
4582                                                NaN     $3.00   

[224 rows x 5 columns]

In [ ]:
(cp['quantity']==2).sum()/len(cp)*100

4.846386845521419

In [ ]:
cp[cp['item_name'].str.contains('Chicken')]

order_id  quantity             item_name  \
4            2         2          Chicken Bowl   
5            3         1          Chicken Bowl   
11           6         1  Chicken Crispy Tacos   
12           6         1    Chicken Soft Tacos   
13           7         1          Chicken Bowl   
...        ...       ...                   ...   
4604      1828         1          Chicken Bowl   
4615      1832         1    Chicken Soft Tacos   
4619      1834         1    Chicken Salad Bowl   
4620      1834         1    Chicken Salad Bowl   
4621      1834         1    Chicken Salad Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75   
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75   
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
...                                                 ...        ...  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75   
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $8.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[1560 rows x 5 columns]

In [ ]:
cp['item_name'].str.contains('Chicken').sum()/len(cp)

0.33751622674167026

In [ ]:
cp['quantity']==2

0       False
1       False
2       False
3       False
4        True
        ...  
4617    False
4618    False
4619    False
4620    False
4621    False
Name: quantity, Length: 4622, dtype: bool

In [ ]:
cp

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN      2.39   
1                                          [Clementine]      3.39   
2                                               [Apple]      3.39   
3                                                   NaN      2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75   

[4622 rows x 5 columns]

In [ ]:
#items which has been ordered in quantity 2

In [ ]:
#percentage of time order made is 2

In [ ]:
(cp['quantity']==2).sum()/len(cp)

0.04846386845521419

In [ ]:
cp['item_name'] == 'chicken'

0       False
1       False
2       False
3       False
4       False
        ...  
4617    False
4618    False
4619    False
4620    False
4621    False
Name: item_name, Length: 4622, dtype: bool

In [ ]:
#.str.contains()---> to check if a paticular strng value is present or not
#.str.replace()-----> to replace an existing character or string

In [ ]:
cp[cp['item_name'].str.contains('Chicken')]

order_id  quantity             item_name  \
4            2         2          Chicken Bowl   
5            3         1          Chicken Bowl   
11           6         1  Chicken Crispy Tacos   
12           6         1    Chicken Soft Tacos   
13           7         1          Chicken Bowl   
...        ...       ...                   ...   
4604      1828         1          Chicken Bowl   
4615      1832         1    Chicken Soft Tacos   
4619      1834         1    Chicken Salad Bowl   
4620      1834         1    Chicken Salad Bowl   
4621      1834         1    Chicken Salad Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...     10.98   
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...      8.75   
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...      8.75   
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     11.25   
...                                                 ...        ...  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...      8.75   
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]      8.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75   

[1560 rows x 5 columns]

In [ ]:
#Number of times chicken item ordered
cp['item_name'].str.contains('Chicken').sum()

1560

In [ ]:
#Percentage of times Chicken ordered

cp['item_name'].str.contains('Chicken').sum()/len(cp)

0.33751622674167026

In [ ]:
# Item ordered with Tacos as one of the ingredients

In [ ]:
cp['item_name'].str.contains('Tacos').sum()/len(cp)*100

7.464301168325401

In [ ]:
cp[cp['item_name'].str.contains('Tacos')]['item_name']

8           Steak Soft Tacos
11      Chicken Crispy Tacos
12        Chicken Soft Tacos
35        Chicken Soft Tacos
36        Chicken Soft Tacos
                ...         
4549        Steak Soft Tacos
4550      Chicken Soft Tacos
4554      Steak Crispy Tacos
4557     Carnitas Soft Tacos
4615      Chicken Soft Tacos
Name: item_name, Length: 345, dtype: object

In [ ]:
# Price

In [ ]:
'5'+'6'+'7'

'567'

In [ ]:
cp['item_price'].sum()

'2.39 3.39 3.39 2.39 16.98 10.98 1.69 11.75 9.25 9.25 4.45 8.75 8.75 11.25 4.45 2.39 8.49 8.49 2.18 8.75 4.45 8.99 3.39 10.98 3.39 2.39 8.49 8.99 1.09 8.49 2.39 8.99 1.69 8.99 1.09 8.75 8.75 4.45 2.95 11.75 2.15 4.45 11.25 11.75 8.75 10.98 8.99 3.39 8.99 3.99 8.99 2.18 10.98 1.09 8.99 2.39 9.25 11.25 11.75 2.15 4.45 9.25 11.25 8.75 8.99 8.99 3.39 8.99 10.98 8.99 1.69 8.99 3.99 8.75 4.45 8.75 8.75 2.15 8.75 11.25 2.15 9.25 8.75 8.75 9.25 8.49 8.99 1.09 9.25 2.95 11.75 11.75 9.25 11.75 4.45 9.25 4.45 11.75 8.75 8.75 4.45 8.99 8.99 3.99 8.49 3.39 8.99 1.09 9.25 4.45 8.75 2.95 4.45 2.39 8.49 8.99 8.49 1.09 8.99 3.99 8.75 9.25 4.45 11.25 4.45 8.99 1.09 9.25 2.95 4.45 11.75 4.45 8.49 2.39 10.98 22.50 11.75 4.45 11.25 4.45 11.25 4.45 11.25 11.25 11.75 9.25 4.45 11.48 17.98 1.69 17.50 4.45 8.49 2.39 17.50 4.45 4.45 11.25 11.75 10.98 8.49 10.98 2.18 11.48 8.49 2.39 4.45 11.25 11.75 8.75 8.49 2.18 8.49 3.39 8.49 8.99 10.98 11.48 8.49 1.09 1.09 9.25 8.75 2.95 9.25 4.45 11.25 11.48 8.49 8.49 8.99 

In [ ]:
# we need to convert string to int
# But first remove $

In [ ]:
cp['item_price']=cp['item_price'].str.replace('$','')
cp


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN      2.39   
1                                          [Clementine]      3.39   
2                                               [Apple]      3.39   
3                                                   NaN      2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75   

[4622 rows x 5 columns]

In [ ]:
cp['item_price'].sum()

'2.39 3.39 3.39 2.39 16.98 10.98 1.69 11.75 9.25 9.25 4.45 8.75 8.75 11.25 4.45 2.39 8.49 8.49 2.18 8.75 4.45 8.99 3.39 10.98 3.39 2.39 8.49 8.99 1.09 8.49 2.39 8.99 1.69 8.99 1.09 8.75 8.75 4.45 2.95 11.75 2.15 4.45 11.25 11.75 8.75 10.98 8.99 3.39 8.99 3.99 8.99 2.18 10.98 1.09 8.99 2.39 9.25 11.25 11.75 2.15 4.45 9.25 11.25 8.75 8.99 8.99 3.39 8.99 10.98 8.99 1.69 8.99 3.99 8.75 4.45 8.75 8.75 2.15 8.75 11.25 2.15 9.25 8.75 8.75 9.25 8.49 8.99 1.09 9.25 2.95 11.75 11.75 9.25 11.75 4.45 9.25 4.45 11.75 8.75 8.75 4.45 8.99 8.99 3.99 8.49 3.39 8.99 1.09 9.25 4.45 8.75 2.95 4.45 2.39 8.49 8.99 8.49 1.09 8.99 3.99 8.75 9.25 4.45 11.25 4.45 8.99 1.09 9.25 2.95 4.45 11.75 4.45 8.49 2.39 10.98 22.50 11.75 4.45 11.25 4.45 11.25 4.45 11.25 11.25 11.75 9.25 4.45 11.48 17.98 1.69 17.50 4.45 8.49 2.39 17.50 4.45 4.45 11.25 11.75 10.98 8.49 10.98 2.18 11.48 8.49 2.39 4.45 11.25 11.75 8.75 8.49 2.18 8.49 3.39 8.49 8.99 10.98 11.48 8.49 1.09 1.09 9.25 8.75 2.95 9.25 4.45 11.25 11.48 8.49 8.49 8.99 

In [ ]:
cp['item_price'].astype(float).sum()

34500.16

In [ ]:
#If we want to reflect changein actual data the write

In [ ]:
cp['item_price']=cp['item_price'].str.replace('$','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


In [ ]:
cp

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN      2.39   
1                                          [Clementine]      3.39   
2                                               [Apple]      3.39   
3                                                   NaN      2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75   

[4622 rows x 5 columns]

In [ ]:
# can we calculate sum now??
# .astype(float)

In [ ]:
cp['item_price'].sum()

'2.39 3.39 3.39 2.39 16.98 10.98 1.69 11.75 9.25 9.25 4.45 8.75 8.75 11.25 4.45 2.39 8.49 8.49 2.18 8.75 4.45 8.99 3.39 10.98 3.39 2.39 8.49 8.99 1.09 8.49 2.39 8.99 1.69 8.99 1.09 8.75 8.75 4.45 2.95 11.75 2.15 4.45 11.25 11.75 8.75 10.98 8.99 3.39 8.99 3.99 8.99 2.18 10.98 1.09 8.99 2.39 9.25 11.25 11.75 2.15 4.45 9.25 11.25 8.75 8.99 8.99 3.39 8.99 10.98 8.99 1.69 8.99 3.99 8.75 4.45 8.75 8.75 2.15 8.75 11.25 2.15 9.25 8.75 8.75 9.25 8.49 8.99 1.09 9.25 2.95 11.75 11.75 9.25 11.75 4.45 9.25 4.45 11.75 8.75 8.75 4.45 8.99 8.99 3.99 8.49 3.39 8.99 1.09 9.25 4.45 8.75 2.95 4.45 2.39 8.49 8.99 8.49 1.09 8.99 3.99 8.75 9.25 4.45 11.25 4.45 8.99 1.09 9.25 2.95 4.45 11.75 4.45 8.49 2.39 10.98 22.50 11.75 4.45 11.25 4.45 11.25 4.45 11.25 11.25 11.75 9.25 4.45 11.48 17.98 1.69 17.50 4.45 8.49 2.39 17.50 4.45 4.45 11.25 11.75 10.98 8.49 10.98 2.18 11.48 8.49 2.39 4.45 11.25 11.75 8.75 8.49 2.18 8.49 3.39 8.49 8.99 10.98 11.48 8.49 1.09 1.09 9.25 8.75 2.95 9.25 4.45 11.25 11.48 8.49 8.49 8.99 

In [ ]:
#No still same Problem
# astype() -> Its a function for pandas to change 
#the existing data type in a panda series

In [ ]:
cp['item_price'].astype(float).sum()

34500.16

In [ ]:
#if you want to reflect change in main dataset

In [ ]:
cp['item_price']=cp['item_price'].astype(float)

In [ ]:
cp

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [ ]:
print(cp['item_price'].sum())
print(cp['item_price'].max())
print(cp['item_price'].min())



34500.16
44.25
1.09


In [ ]:
#Item with maximum price
#idxmax() works same as argmax() but argmax() defined for numpy

In [ ]:
cp.loc[45]['item_name']

'Chicken Burrito'

In [ ]:
cp.loc[45]

order_id                                                             21
quantity                                                              1
item_name                                               Chicken Burrito
choice_description    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
item_price                                                        10.98
Name: 45, dtype: object

In [ ]:
cp['item_price'].idxmax()

3598

In [ ]:
cp.loc[3598]['item_name']

'Chips and Fresh Tomato Salsa'

In [ ]:
#item with minimum price

In [ ]:
cp['item_price'].idxmin()

28

In [ ]:
cp.loc[28]['item_name']

'Canned Soda'

In [ ]:
#frequency of item ordered
#value_counts()->counts the existence of unique values in a pandas series

In [ ]:
#cp['item_name'].value_counts()

In [ ]:
cp['item_price'].value_counts()

8.75     730
11.25    521
9.25     398
4.45     349
8.49     311
        ... 
13.35      1
7.50       1
4.36       1
11.80      1
11.49      1
Name: item_price, Length: 78, dtype: int64

In [ ]:
#Now we will discuss Null Values   NaN

In [ ]:
#How to figure out NULL values

In [ ]:
cp.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
#How to treat NULL values
# Drop the row containing NULL values or
# Drop the column containing NULL values or
# Fill the NULL values

In [ ]:
#Droping column

In [ ]:
print(cp.shape)
print(cp.columns)
cpc=cp.dropna(axis=1)#Column drop
print(cpc.shape)
print(cpc.columns)

(4622, 5)
Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')
(4622, 4)
Index(['order_id', 'quantity', 'item_name', 'item_price'], dtype='object')


In [ ]:
print(cp.shape)
cpc=cp.dropna(axis=0)#Column drop
print(cpc.shape)

(4622, 5)
(3376, 5)


In [ ]:
#Drop row

In [ ]:
#Fill Null Values


In [ ]:
#cp[cp['choice_description'].str.contains['Tomato']]

In [ ]:
cp

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

In [ ]:
cp['choice_description']=cp['choice_description'].fillna('abcd')

In [ ]:
cp['choice_description'].str.contains['Apple']

TypeError: ignored

In [ ]:
#Another dataset

In [ ]:
import pandas as pd


In [ ]:
movies=pd.read_csv('http://bit.ly/imdbratings')
movies.head(10)

star_rating                                          title content_rating  \
0          9.3                       The Shawshank Redemption              R   
1          9.2                                  The Godfather              R   
2          9.1                         The Godfather: Part II              R   
3          9.0                                The Dark Knight          PG-13   
4          8.9                                   Pulp Fiction              R   
5          8.9                                   12 Angry Men      NOT RATED   
6          8.9                 The Good, the Bad and the Ugly      NOT RATED   
7          8.9  The Lord of the Rings: The Return of the King          PG-13   
8          8.9                               Schindler's List              R   
9          8.9                                     Fight Club              R   

       genre  duration                                        actors_list  
0      Crime       142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      Crime       175    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2      Crime       200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3     Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4      Crime       154  [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5      Drama        96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
6    Western       161  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
7  Adventure       201  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
8  Biography       195  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...  
9      Drama       139  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...

In [ ]:
#extract movies with genre(crime or action or comedy)
# and duration less than 160
#extract all movies of Actor 'Tim Robbins'
#Movie with longest duration


In [ ]:
movies[((movies['genre']=='Crime')|(movies['genre']=='Comedy')|(movies['genre']=='Action')) & (movies['duration']<160) &(movies['star_rating']>8)]

star_rating                                           title  \
0            9.3                        The Shawshank Redemption   
3            9.0                                 The Dark Knight   
4            8.9                                    Pulp Fiction   
11           8.8                                       Inception   
12           8.8  Star Wars: Episode V - The Empire Strikes Back   
..           ...                                             ...   
285          8.1                                Bringing Up Baby   
287          8.1                                 His Girl Friday   
290          8.1                                       Prisoners   
293          8.1                                       Duck Soup   
296          8.1                                  The Wild Bunch   

    content_rating   genre  duration  \
0                R   Crime       142   
3            PG-13  Action       152   
4                R   Crime       154   
11           PG-13  Action       148   
12              PG  Action       124   
..             ...     ...       ...   
285       APPROVED  Comedy       102   
287       APPROVED  Comedy        92   
290              R   Crime       153   
293         PASSED  Comedy        68   
296              R  Action       145   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
11   [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...  
12   [u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...  
..                                                 ...  
285  [u'Katharine Hepburn', u'Cary Grant', u'Charle...  
287  [u'Cary Grant', u'Rosalind Russell', u'Ralph B...  
290  [u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ...  
293    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
296  [u'William Holden', u'Ernest Borgnine', u'Robe...  

[102 rows x 6 columns]

In [ ]:
movies['duration'].max()

242

In [ ]:
movies[movies['actors_list'].str.contains('Tim Robbins')]['title']

0      The Shawshank Redemption
365                Mystic River
611                  Short Cuts
693                  The Player
819              Jacob's Ladder
Name: title, dtype: object

In [ ]:
#Another Method

In [ ]:
movies[movies['genre'].isin(['Comedy','Action','Crime'])& (movies['star_rating']>8) & (movies['duration']<160)]

star_rating                                           title  \
0            9.3                        The Shawshank Redemption   
3            9.0                                 The Dark Knight   
4            8.9                                    Pulp Fiction   
11           8.8                                       Inception   
12           8.8  Star Wars: Episode V - The Empire Strikes Back   
..           ...                                             ...   
285          8.1                                Bringing Up Baby   
287          8.1                                 His Girl Friday   
290          8.1                                       Prisoners   
293          8.1                                       Duck Soup   
296          8.1                                  The Wild Bunch   

    content_rating   genre  duration  \
0                R   Crime       142   
3            PG-13  Action       152   
4                R   Crime       154   
11           PG-13  Action       148   
12              PG  Action       124   
..             ...     ...       ...   
285       APPROVED  Comedy       102   
287       APPROVED  Comedy        92   
290              R   Crime       153   
293         PASSED  Comedy        68   
296              R  Action       145   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
11   [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...  
12   [u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...  
..                                                 ...  
285  [u'Katharine Hepburn', u'Cary Grant', u'Charle...  
287  [u'Cary Grant', u'Rosalind Russell', u'Ralph B...  
290  [u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ...  
293    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
296  [u'William Holden', u'Ernest Borgnine', u'Robe...  

[102 rows x 6 columns]